version: '3.8'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: '127.0.0.1'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: "user:1:1"

  mysql:
    image: 'mysql:8.0.11'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=skilltracker
      - MYSQL_PASSWORD=skilltracker
      - MYSQL_DATABASE=skilltracker
      #- MYSQL_USER=root
    ports:
      - "3307:3306"


  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data_container:/var/lib/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
